[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mining_drs"
version = "0.1.0"
description = "A dynamic simulation engine for mining operations."
authors = [
    { name = "mining-drs Team" }
]
requires-python = ">=3.8"
dependencies = [
    "pandas>=1.0",
    "numpy>=1.20",
    "matplotlib>=3.5",
    "rich>=13.0"
]

[project.optional-dependencies]
mining = ["gstools>=1.4"]
dev = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
    "pytest-benchmark"
]
docs = [
    "mkdocs>=1.5",
    "mkdocs-material>=9.4",
    "mkdocstrings[python]>=0.24"
]
rl = [
    "torch>=2.0",
    "gymnasium>=0.28",
    "wandb",
    "tensordict",
    "einops",
    "rl-stuff"
]
all = ["mining_drs[mining,rl,dev,docs]"]

[tool.hatch.build.targets.wheel]
packages = ["drs", "drs_mining"]

[tool.coverage.run]
source = ["drs", "drs_mining"]
omit = [
    "tests/**",
    "examples/**",
    "**/__init__.py",
]

[tool.coverage.report]
omit = [
    "tests/**",
    "examples/**",
    "**/__init__.py",
]
